# Generated by Django 4.1 on 2023-05-05 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='avator',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
