# Generated by Django 4.1 on 2023-05-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('public', '公開'), ('private', '非公開')], default='public', max_length=10),
        ),
    ]
